### ISSUE TITLE
Modules fail to build with restrictive umask

### ISSUE THREAD

**Issue by Dekedro** [jirutka/akms#8]
Setup:
- akms 0.1.1 (Alpine)
- have umask set to 077
- try building anything directly with akms, fails with "bwrap: Can't find source path /tmp/akms/\<timestamp>/overlay: Permission denied"

Looks like directories created by script are just not readable by akms user. Happy to provide more info if needed.

**Comment by jirutka** [comment]
Should be fixed now. Thanks for reporting it!
