### ISSUE TITLE
Login shell is used when building modules

### ISSUE THREAD

**Issue by Dekedro** [jirutka/akms#9]
AKMS uses `su -l` to switch to a build user. If a system has custom "/etc/profile", unrelated actions might be executed during the build process. It could create confusion (e.g., print unrelated messages) or interfere with AKMS (by setting variables to unexpected values).

`su -l` could be avoided by using `--clearenv`/`--setenv` from bubblewrap (or `env -i`) and setting variables manually. Looks like setting PATH to "/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin" is enough for simple modules, however more variables might be needed in some cases?

EDIT: It might be simpler to clear environment and then execute commands in a new non-login shell. However, it might complicate argument handling in "akms-runas".

**Comment by jirutka** [comment]
Should be fixed now. Thanks for reporting it!
